### ISSUE TITLE
[LUNATIX] Lunatix - Stack at initial splash screen, can't progress into game

### ISSUE THREAD

**Issue by ryanfantus** [mbbsemu/MBBSEmu#490] opened 2021-05-31 23:32 UTC
**Module Information**
* LUNATIX
* Lunatix
* 5.3f

**Describe the bug**
Can't get past intro screen after launching game. Feels like a regression as this used to work in https://github.com/mbbsemu/MBBSEmu/releases/tag/v1.0-alpha-010421

**To Reproduce**
1. Launch MBBSEmu
2. Either telnet/rlogin into the MBBSEmu menu _or_ directly to the rlogin game port for Lunatix
3. See ansi splash screen/info screen
4. Press enter or any other key to continue and note that you're stuck at this screen

**Expected behavior**
Game logic continues and allows you to either create a character (if you haven't already) or continue gaming from previous login

**Screenshots**
![image](https://user-images.githubusercontent.com/1007329/120248822-8aa02500-c22d-11eb-967a-abd3b0cc23e9.png)

**Software Information:**
- OS: Ubuntu 20.04 amd64
- Telnet Client: NetRunner as well as linux telnet and linux rlogin

**Comment by enusbaum** [comment] 2021-06-02 23:56
This looks like a regression being caused by `btuinj` setting state on the channel to `240` (delayed execution) and not persisting that state after the `sttrou` completes execution.

**Comment by enusbaum** [comment] 2021-06-03 11:35
The right thing to do to fix this regression is actually implement `Status` as a FIFO Queue, as it is in MBBS/WG. 

When a module exits a routine successfully, we need to set the status to `0` and have an empty status queue. The main loop of the MBBS process should check to see if there's a status code in the queue and then take action if there is. 

In this case, Lunatix is using `btuinj` to inject a status of `240` to the Status queue (deferred execution), then programmatically setting a status of `1`. This means on the next iteration of the MBBSEmu event loop, it should dequeue and process the `240`, where as right now because `Status` is a ushort property, it's only seeing the last value, which is `1` -- resulting in this defect.

![image](https://user-images.githubusercontent.com/1139047/120638551-40da5900-c43e-11eb-9047-8c71afec871c.png)

**Comment by enusbaum** [comment] 2021-06-22 14:12
Have this fixed in the branch `status-fifo-queue`, but I'm working through getting Blox working properly with its implementation of `btuech` and `btuche` and how those impact status. 

Once I get Blox fixed we should be good to go!

**Closed** 2021-07-09 17:19 UTC
Labels: bug, module
